# Generated by Django 6.0.1 on 2026-02-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisuggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('description', 'Description Improvement'), ('priority', 'Priority Suggestion'), ('subtasks', 'Subtasks Generation'), ('coach', 'Productivity Coaching'), ('search', 'Smart Search')], max_length=20),
        ),
    ]
