# Generated by Django 6.0.1 on 2026-02-26 11:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_aisuggestion_suggestion_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('color', models.CharField(choices=[('#c3392b', 'Red'), ('#2ecc71', 'Green'), ('#3498db', 'Blue'), ('#f39c12', 'Orange'), ('#9b59b6', 'Purple'), ('#1abc9c', 'Teal'), ('#e74c3c', 'Crimson'), ('#34495e', 'Dark')], default='#3498db', max_length=7)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('description', 'Description Improvement'), ('priority', 'Priority Suggestion'), ('subtasks', 'Subtasks Generation'), ('coach', 'Productivity Coaching'), ('search', 'Smart Search'), ('tags', 'Auto Tagging')], max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.tag'),
        ),
    ]
