# Generated by Django 6.0.1 on 2026-02-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tag_alter_aisuggestion_suggestion_type_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisuggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('description', 'Description Improvement'), ('priority', 'Priority Suggestion'), ('subtasks', 'Subtasks Generation'), ('coach', 'Productivity Coaching'), ('search', 'Smart Search'), ('tags', 'Auto Tagging'), ('wizard', 'AI Task Wizard')], max_length=20),
        ),
    ]
